// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAyrWlbF9DoSHDBNivuJMoe6jWahKgjbc',
    appId: '1:1062539815128:web:bf43fc35f14ec91e7acfad',
    messagingSenderId: '1062539815128',
    projectId: 'social-study-ai',
    authDomain: 'social-study-ai.firebaseapp.com',
    storageBucket: 'social-study-ai.firebasestorage.app',
    measurementId: 'G-K4ZB6HZK0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-bA0kMK-YTC2tm2xnay72Q59Wxd2bZY',
    appId: '1:1062539815128:android:3f905b929022ae307acfad',
    messagingSenderId: '1062539815128',
    projectId: 'social-study-ai',
    storageBucket: 'social-study-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPT3I3zz3e4IqBVynFGrS8kKgTKR0o8D8',
    appId: '1:1062539815128:ios:91dbd62504e4e3c67acfad',
    messagingSenderId: '1062539815128',
    projectId: 'social-study-ai',
    storageBucket: 'social-study-ai.firebasestorage.app',
    iosBundleId: 'com.example.socialStudyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPT3I3zz3e4IqBVynFGrS8kKgTKR0o8D8',
    appId: '1:1062539815128:ios:91dbd62504e4e3c67acfad',
    messagingSenderId: '1062539815128',
    projectId: 'social-study-ai',
    storageBucket: 'social-study-ai.firebasestorage.app',
    iosBundleId: 'com.example.socialStudyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAyrWlbF9DoSHDBNivuJMoe6jWahKgjbc',
    appId: '1:1062539815128:web:590faf635eb3acd07acfad',
    messagingSenderId: '1062539815128',
    projectId: 'social-study-ai',
    authDomain: 'social-study-ai.firebaseapp.com',
    storageBucket: 'social-study-ai.firebasestorage.app',
    measurementId: 'G-1S8RK8JN9B',
  );
}
